### ISSUE TITLE
Randomly stopping at a certain point.

### ISSUE THREAD

**Issue by euiruhieer** [xtekky/TikTok-Checker#3]
The checker stops at a random number. For example, the first time, it stopped at 1407 invalid, second time it stopped at 507 invalid. Dunno if it's me doing something wrong.

**Comment by ghost** [comment]
> The checker randomly stops at a random number. For example, the first time, it stopped at 1407 invalid, second time it stopped at 507 invalid. Dunno if it's me doing something wrong.

its the proxies prolly.

**Comment by euiruhieer** [comment]
> > The checker randomly stops at a random number. For example, the first time, it stopped at 1407 invalid, second time it stopped at 507 invalid. Dunno if it's me doing something wrong.
> 
> its the proxies prolly.

how would that work
